### ISSUE TITLE
field name rules

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-csv-structure#2]
* Documentation reference (URL): https://github.com/ess-dive-community/essdive-csv-structure/blob/master/csv_detailed_guide.md#field-names
* Submitter: Kim Ely
* Justification (why is this change necessary?): could cause coding/data assimilation issues

I suggest the following changes: It's not the end of the world, but apparently R doesn't particularly like column names that start with a number (i.e. 0-9). Perhaps recommend to not use numbers as the first character?

**Comment by tvelliquette** [comment]
@regnans I was thinking we had that in the documentation at some point but apparently we never did. How would R handle it if the column name had double quotes for a column that started with a number?

**Comment by regnans** [comment]
I don't know how R would handle double quotes. (R beginner here!). Although, my feeling is that this could be messy and best avoided. Potentially more problematic than using numbers. Could it work to _recommend_ to not start column names with numbers, but allow it if the data uploader needed to do this?

**Comment by tvelliquette** [comment]
@robcrystalornelas check the text for this section to see if it captures not starting the field name with a number

I also added text to say don't use CamelCase. Question - I couldn't recall - did ess-dive decide "don't use CamelCase" or "recommend not using CamelCase"? I know this decision came right before the workshop.

**Comment by tvelliquette** [comment]
@robcrystalornelas Instead of "Field" the term "column" appears throughout the FLMD and dd instructions. Should I change column to field or should I change it to "column/row name"

**Comment by wavingtowaves** [comment]
I'll modify wording a bit then close this issue. Ultimately, we decided that groups, as much as possible should switch to underscores rather than camelcase. But there are definitely exceptions for example, when terms are considered a single entity 'dateTime' or when reporting formats are following other standards that prefer to use camelCase (e.g., sample metadata).
