### ISSUE TITLE
daylight savings time

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-csv-structure#3]
**Submitter**:

I suggest the following changes:
The requirement in https://github.com/ess-dive-community/essdive-csv-structure/blob/master/csv_detailed_guide.md#temporal-data
to "Do not report time using Daylight Savings Time." is actually problematic for Alaska work. This is standard "local time" and we have been using this for many years. To edit could cause many errors. Can this be OK as long as the UTC offset is properly reported?

**Comment by tvelliquette** [comment]
@regnans I will have to send this over to @robcrystalornelas since we worked quite a bit with ESS-DIVE on this one. According to current instructions, there could be UTC in standard time column in addition to the UTC daylight savings column although possibly confusing.

**Comment by charuleka** [comment]
Our current standard supports @regnans use case. We just need to change the instructions. The intent isn't to prevent standard local time which is actually daylight savings, it is to prevent people from switching midway in the time series to daylight savings. So as long as a UTC time zone is recorded, it is ok.

**Comment by regnans** [comment]
To clarify, data reported in local daylight savings time is limited to data sets collected only during the summer period. We would not use daylight savings time for sensors operating all year (hopefully we have some of that data coming, but since the cameras have been out since 2019 we don't know if they are still working!!!)

**Comment by tvelliquette** [comment]
@robcrystalornelas can you confirm if the text reflects the change needed? And is this issue done?

**Comment by wavingtowaves** [comment]
Yes, text in both detailed and quick guides are updated to reflect changes we wanted to make.  We can close out this issue.
