### ISSUE TITLE
Time reporting format

### ISSUE THREAD

**Issue by kristinboye** [ess-dive-community/essdive-csv-structure#5]
* Documentation reference (URL): https://github.com/ess-dive-community/essdive-csv-structure/blob/master/csv_quick_guide.md; https://github.com/ess-dive-community/essdive-hydrologic-monitoring/blob/main/template_DataFile.csv; https://github.com/ess-dive-community/essdive-soil-respiration/blob/main/data_reporting_format_guide.md; https://github.com/ess-dive-community/essdive-leaf-gas-exchange/blob/master/docs/definedVariables.md; https://github.com/ess-dive-community/essdive-sample-id-metadata/blob/master/guide.md#collection-date
* Submitter: Kristin Boye
* Justification (why is this change necessary?): there is no consistency in the format for how date and time is reported between the various "reporting formats"

I suggest the following changes: Could we agree on an "ESS-DIVE central" format for how to report date and time? Looking through the currently uploaded instructions (CSV, Sample ID, Soil Respiration, Hydrologic Monitoring, Leaf Gas exchange) there are as many ways of reporting date and time as there are reporting formats (although all recommend UTC and request UTC offset if using local time). I personally like (and think it would make things more script-friendly as we are trying to limit the use of special characters????) to keep delimiters out of it (as proposed in the soil respiration reporting format) and simply use up to 12 digits (YYYYMMDDHHMMSS) to the level of appropriate resolution for the data, but as long as we agree on what we should require/recommend I think that would help a lot...

**Comment by tvelliquette** [comment]
Agreed upon this format with a space between date and time: YYYY-MM-DD hh:mm:ss

I can add this information to the instructions.

**Comment by wavingtowaves** [comment]
@tvelliquette , when we get all of the wording updated, we can close out this issue.

**Comment by tvelliquette** [comment]
@robcrystalornelas I added to quick guide and detailed guide info about it being okay to use two fields for date and time under temporal data plus added the space in the ISO standard format

Under temporal range I added text about naming fields "("dateTime_start and dateTime_end" or "time_start and time_end")

**Comment by wavingtowaves** [comment]
I just finished reviewing the guides for this term. Everything looks good. I added in some quotes to the example you provide above, so that people know "dateTime_start" and "dateTime_end" are two different columns.

**Comment by tvelliquette** [comment]
close if done

**Comment by wavingtowaves** [comment]
Closing
