### ISSUE TITLE
Possible to use semicolon in list?

### ISSUE THREAD

**Issue by wavingtowaves** [ess-dive-community/essdive-csv-structure#6]
* Documentation reference (URL): https://github.com/ess-dive-community/essdive-csv-structure/blob/master/csv_quick_guide.md#delimiter
* Submitter: Rob C-O
* Justification (why is this change necessary?): 

Is there a reason why we shouldn't use semicolon in (for example) a list of terms within a CSV cell?  I reviewed notes on this reporting format and did not find a reason why semicolons shouldn't be used to separate words in a list.

I suggest the following changes:
Right now, the CSV reporting format suggests: "For commas not meant to be a delimiter (e.g. used within a cell), use a vertical bar"

could be changed to: "For commas not meant to be a delimiter (e.g. used within a cell), use a vertical bar or semicolon"

@charuleka and @vchendrix Is there a use case we can think of where semicolon's should not be used as part of a list of terms?

**Comment by tvelliquette** [comment]
I can add the above phrasing to the instructions that vertical bar and semicolon are an alternative.

I don't believe we need to record what people are using as long as they follow the instructions there shouldn't be a problem.

**Comment by wavingtowaves** [comment]
OK, that sounds great @tvelliquette !

**Comment by tvelliquette** [comment]
@robcrystalornelas I added the text about semicolon to the quick guide and the detailed guide. I didn't think I could edit the quick guide but I could!

**Comment by wavingtowaves** [comment]
Nice! Sounds great @tvelliquette do you want to go ahead and close this issue or should I?
