### ISSUE TITLE
N/A values in R

### ISSUE THREAD

**Issue by wavingtowaves** [ess-dive-community/essdive-csv-structure#7]
**Submitter**: @robcrystalornelas and @JEDamerow 

I suggest the following changes:
The "N/A" requirement that the CSV format recommends for missing values requires additional step in R. 

R specifically uses "NA" for missing values rather than N/A

**Comment by regnans** [comment]
To clarify, is this issue suggesting a change from using N/A to NA, or a change in the wording to the documentation? 

(I'm about to get busy with preparation of a bunch of dataset, so would like to get this correct first time. )
thanks, Kim

**Comment by tvelliquette** [comment]
I recall this was specifically requested by Deb to use "N/A". I wondered about why and did some additional research and found that N/A can less often be seen or performed as a mis-type and it also cannot be seen as an abbreviation for North America although I'm not sure if these are the reasons behind Deb's request.

**Comment by wavingtowaves** [comment]
Sounds good @regnans we'll work on this and keep you posted. @tvelliquette thanks for providing the context on this issue. @charuleka could you help us determine best course of action here.

Here's a quick reproducible example. @JEDamerow could you make sure I've outline the problem sufficiently here.

```r
# Create dataframe with both NA and N/A to indicate missing values.
dat <- data.frame(var1=c(1.1,4.3,1.032),
                   var2=c(12.1,NA,15.4),
                   var3=c("N/A", 40.1,67.5))

# R counts 1 NA in var2, but no N/As in var3
sum(is.na(dat$var2))
> [1] 1
sum(is.na(dat$var3))
> [1] 0

# Converting var3 column to numeric also converts N/A to NA, then R counts in the NA in var3 appropriately.
dat$var3 <- as.numeric(dat$var3)
> Warning message:
> NAs introduced by coercion 
sum(is.na(dat$var3))
> [1] 1
```

**Comment by tvelliquette** [comment]
In the example, "NA" and "N/A" are being used in a numeric field. Empty cells in numeric fields should be "-9999".

**Comment by wavingtowaves** [comment]
Thanks for clarifying, Terri.  Then regardless of the missing value code people use: "-9999" and missing character "N/A" they will have to write some code to identify those missing values either way.

**Comment by wavingtowaves** [comment]
@regnans just following-up on this issue and letting you know that we will keep same recommendations as in the CSV v1.0.0 guidelines which is `N/A` for missing character and `-9999` for missing numeric data.
